# This file goes in: my-erc721c-collection/foundry.toml
# NOT in: my-erc721c-collection/lib/creator-token-contracts/foundry.toml

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# Remappings for dependencies
remappings = [
    "@limitbreak/creator-token-contracts/=lib/creator-token-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# ApeChain network configurations
[rpc_endpoints]
apechain = "https://apechain.calderachain.xyz/http"
curtis = "https://curtis.rpc.caldera.xyz/http"

# Etherscan configuration (optional - only needed for contract verification)
# Uncomment and add your API keys when you're ready to verify contracts
# [etherscan]
# apechain = { key = "YOUR_API_KEY_HERE", url = "https://apechain.calderaexplorer.xyz/api" }
# curtis = { key = "YOUR_API_KEY_HERE", url = "https://curtis.calderaexplorer.xyz/api" }